## Setup Environments

This section describes what, how, and where to install the software needed for this lab. This lab is designed for a BYOL (Brying Your Own Laptop) style hands-on-lab.

### Hardware

. Operating System: Mac OS X (10.8 or later), Windows 7 (SP1), Fedora (21 or later)
. Memory: At least 4 GB+, preferred 8 GB

### Environment

. Edit `/etc/resolv.conf` (Mac OS or Linux) and leave it as:

TODO - Add instructions for Windows
+
[source, text]
----
nameserver <INSTRUCTOR IP ADDRESS>
----


### Software

. Java: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8u45]
. Web Browser
.. https://www.google.com/chrome/browser/desktop/[Chrome]
.. link:http://www.getfirefox.com[Firefox]

### Git Client

Install Git Client as explained at: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

You can find GIT for Windows at: http://classroom.example.com:8082/downloads/Git-1.9.5-preview20150319.exe

### Maven

. Download Apache Maven from http://classroom.example.com:8082/downloads/apache-maven-3.3.3-bin.zip.
. Unzip to a directory of your choice and add it to the `PATH`.

### VirtualBox

Docker currently runs natively on Linux. It can be configured to run in a virtual machine on Mac or Windows. This is why Virtualbox is a requirement for Mac or Windows.

Downloads are available from http://classroom.example.com:8082/downloads/virtualbox/.

[WARNING]
====
Linux Users

. Have your kernel updated
. Users should have the GNU compiler, build and header files for your current Linux kernel
. Create a `/usr/src/linux` link to the current kernel source
====

### Vagrant

Download Vagrant from http://classroom.example.com:8082/downloads/vagrant/ and install.

### Docker Machine

Docker Machine makes it really easy to create Docker hosts on your computer, on cloud providers and inside your own data center. It creates servers, installs Docker on them, then configures the Docker client to talk to them.

[source, text]
----
# Mac
sudo curl -L http://classroom.example.com:8082/downloads/docker/docker-machine_darwin-amd64 -o /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

# Linux (Manual install)
sudo curl -L  http://classroom.example.com:8082/downloads/docker/docker-machine_linux-amd64 -o /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine

#Windows
curl http://classroom.example.com:8082/downloads/docker/docker-machine.exe
----

### Create Lab Docker Host

. Create Docker Host to be used in the lab:
+
[source, text]
----
docker-machine create --driver=virtualbox --virtualbox-boot2docker-url=http://classroom.example.com:8082/downloads/boot2docker.iso --engine-insecure-registry=classroom.example.com:5000 lab
eval "$(docker-machine env lab)"
----
+
Use the following command on Windows:
+
[source, text]
----
(docker-machine env lab --shell cmd
----
+
And then execute all the `set` commands.
+
. To make it easier to start/stop the containers, an entry is added into the host mapping table of your operating system. Find out the IP address of your machine:
+
[source, text]
----
docker-machine ip lab
----
+
This will provide the IP address associated with the Docker Machine created earlier.
+
. Edit `/etc/hosts` (Mac OS or Linux) or `C:\Windows\System32\drivers\etc\hosts` (Windows) and add:
+
[source, text]
----
<IP ADDRESS>  dockerhost
----

### Docker Client

Docker Client is used to communicate with Docker Host.

[source, text]
----
# Mac
sudo curl -L http://classroom.example.com:8082/downloads/docker/docker-latest-mac -o /usr/local/bin/docker
chmod +x /usr/local/bin/docker

# Linux
sudo curl -L http://classroom.example.com:8082/downloads/docker/docker-latest-linux -o docker-latest-linux
chmod +x /usr/local/bin/docker

# Windows
curl -L http://classroom.example.com:8082/downloads/docker/docker-1.8.2.exe -o docker.exe
----

### WildFly

. Download WildFly 9.0.1 from http://classroom.example.com:8082/downloads/wildfly-9.0.1.Final.zip.
. Install it by extracting the archive.

### JBoss Developer Studio 9.0.0.GA

To install JBoss Developer Studio stand-alone, complete the following steps:

. Download http://classroom.example.com:8082/downloads/jboss-devstudio-9.0.0.GA-installer-standalone.jar[JBDS 9.0.0.GA].

. Start the installer as:
+
[source, text]
----
java -jar <JAR FILE NAME>
----
+
Follow the on-screen instructions to complete the installation process.

### Create Docker Swarm Cluster

Create Docker Swarm cluster as:

[source, text]
----
docker run classroom.example.com:5000/swarm create
----

This will generate a token. Use this token to create a Swarm Master.

[source, text]
----
docker-machine create -d virtualbox --virtualbox-boot2docker-url=http://classroom.example.com:8082/downloads/boot2docker.iso --engine-insecure-registry=classroom.example.com:5000 --swarm --swarm-master --swarm-discovery token://<token> swarm-master
----

Detailed explanation for this is available in <<Docker_Swarm>>.
